### ISSUE TITLE
Hang in VSCode's integrated terminal

### ISSUE THREAD

**Issue by kidonng** [dalance/procs#142]
procs will hang if running in VSCode's integrated terminal, which is powered by [xterm.js](https://github.com/xtermjs/xterm.js):

```
$ procs --debug 
Info: View::new [0.134s]
Info: view.filter [0.000s]
Info: view.adjust [0.000s]

(Hang)
```

I haven't test other programs that use xterm.js, but given that I don't have such issue with other programs, I guess procs is to blame.

**Comment by dalance** [comment]
I tried to reproduce it on the following environment, but all cases work fine.

* Linux / zsh
* Windows / PowerShell
* Windows / Command Prompt

Could you provide your environment?

**Comment by kidonng** [comment]
Sorry, my fault. I'm using the latest VSCode (1.56.0) on macOS 11.4 (20F5055c). This doesn't seem to be related to shell as I get the same result in bash/zsh/fish.

**Comment by dalance** [comment]
Could you try `procs --pager disable --theme dark`?

**Comment by kidonng** [comment]
If I disable the pager, it works. 👍

**Comment by dalance** [comment]
Hmm, How about `procs | less -SR`?

**Comment by kidonng** [comment]
No issues.

**Comment by dalance** [comment]
Could you try the following repository?
https://github.com/dalance/pager-test

```
$ git clone https://github.com/dalance/pager-test
$ cd pager-test
$ cargo run
```

If you don't have Rust environment, I'll setup GitHub Actions for macOS binary later.

**Comment by kidonng** [comment]
You don't have to setup a CI, however I'm outside, will reply in an hour or two.

**Comment by kidonng** [comment]
The demo runs with no issue:
![image](https://user-images.githubusercontent.com/44045911/117618870-23003800-b1a1-11eb-892c-3a6e3cad20b4.png)

**Comment by kidonng** [comment]
Looks like the pager no longer works:

![image](https://user-images.githubusercontent.com/44045911/117619930-758e2400-b1a2-11eb-82bf-8eb9975e627d.png)

https://user-images.githubusercontent.com/44045911/117620235-dd446f00-b1a2-11eb-90e5-84b88fd34937.mov

Also worth mentioning, setting `LESSCHARSET=utf-8` doesn't help with `procs`.

**Comment by dalance** [comment]
Could you try to change `less` to the absolute path of `less` like below?

```rust
use pager::Pager;

fn main() {
    Pager::with_pager("/usr/bin/less -SR")
        .pager_envs(&["LESSCHARSET=utf-8"])
        .setup();
    println!("Hello, world!");
}
```

**Comment by dalance** [comment]
I fixed another bug, and released v0.11.6.
Is there any behaviour changing?

**Comment by kidonng** [comment]
Same issue.

**Comment by dalance** [comment]
Please let me reconfirm.
How about the followings?

`procs --pager disable`
`procs --theme dark`
`procs --pager disable --theme dark`

**Comment by kidonng** [comment]
I guess that's it. As long as you use `--theme auto` or don't specify `--theme`, it hangs.

**Comment by dalance** [comment]
Ok.
Could you try the following repository?
https://github.com/dalance/termbg

```
$ git clone https://github.com/dalance/termbg
$ cd termbg
$ cargo run
```

**Comment by kidonng** [comment]
```
Check terminal background color
  Term : XtermCompatible
  Color: detection failed Timeout { source: Timeout }
  Theme: detection failed Timeout { source: Timeout }
```

**Comment by dalance** [comment]
I tried to fix.
Could you try the latest commit of procs?

https://github.com/dalance/procs/commit/00a3be3ac51015337f7c1606a5f157474986acf5

**Comment by kidonng** [comment]
The latest commit works 👍
Is this some kind of issue I can report to VSCode/xterm.js?

**Comment by dalance** [comment]
Thanks!
This is because VSCode/xterm.js doesn't support background color query by the xterm compatible way.
I think this is not bug, may be feature request.

**Comment by kidonng** [comment]
Maybe I will open an issue there later. Thanks for your patience and resolving the issue with me!

**Comment by dalance** [comment]
I released v0.11.7.

**Comment by AnabasisXu** [comment]
> Could you try `procs --pager disable --theme dark`?

The same problem still exists for the latest version on Cygwin with Zsh:

```
❯ procs --version
procs "0.14.8 ( rev: 368d14a, rustc: 1.82.0, build at: 2024/10/23 10:23:55 )"
```

At first I also thought it was due to PAGER configuration, then I tested `--theme auto` and `dark`. Whenever theme is not set to dark, procs will hang. 

By `hang` I mean only by `Ctrl+C` or `q` will Zsh show the correct output. Use `--theme dark` will solve the problem (no need to set `--pager disable`).

The same problem occurs for Windows CMD, but not for Cmder.

So I use procs with the following alias:

`alias procs='procs --theme dark'`
